language: node_js
node_js:
- "0.12"
- "0.11"
- "0.10"

before_install: bundle install

after_script:
- istanbul cover jasmine-node --captureExceptions spec/ && cat ./coverage/report-lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js
