language: node_js
node_js:
- '0.12'
# - '0.11'
# - '0.10'
before_install: bundle install
after_script:
- cat ./coverage/report-lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- cat ./coverage/report-lcov/lcov.info | ./node_modules/.bin/codacy-coverage
addons:
  sauce_connect: true
cache:
  directories:
    - node_modules
    - bower_components
notifcations:
  webhooks: https://webhooks.gitter.im/e/0d3dd621350d780c1bf7
